version: "3.8"

services:

  app-main-node:
    build:
      context: .github/docker
      dockerfile: development/node-main-app/Dockerfile
    container_name: app-main-node
    volumes:
      - ./src:/app
    working_dir: /app/sources/main-app

  app-php-cli:
    build:
      context: .github/docker
      dockerfile: development/php-cli/Dockerfile
    container_name: app-php-cli
    volumes:
      - ./src:/app
